version: "2"
authtoken: 30JunzmG2Ou7AaR2LcPfLh2wntY_5XHQe6K3WjdL1LsB6MgWU

tunnels:
  gadingpro-backend:
    proto: http
    addr: 5000
  gadingpro-frontend:
    proto: http
    addr: 5173
  gadingpro-admin:
    proto: http
    addr: 3000
